import { create } from 'zustand'
import { persist } from 'zustand/middleware'

type Theme = 'light' | 'dark'
type Language = 'zh' | 'en'

interface ThemeState {
  theme: Theme
  setTheme: (theme: Theme) => void
  language: Language
  setLanguage: (language: Language) => void
}

export const useThemeStore = create<ThemeState>()(
  persist(
    (set) => ({
      theme: 'light',
      setTheme: (theme) => set({ theme }),
      language: 'zh',
      setLanguage: (language) => set({ language }),
    }),
    {
      name: 'theme-storage',
    }
  )
)

export const translations = {
  zh: {
    forumTitle: '轮胎法规分享论坛',
    home: '首页',
    userCenter: '用户中心',
    settings: '设置',
    favorites: '我的收藏',
    history: '历史记录',
    messages: '消息记录',
    accountSettings: '账号设置',
    login: '登录',
    logout: '退出登录',
    username: '用户名',
    password: '密码',
    newPassword: '新密码（留空则不修改）',
    saveSettings: '保存设置',
    loginSuccess: '登录成功',
    loginFailed: '登录失败',
    pleaseLogin: '请先登录',
    createTopic: '新建帖子',
    search: '搜索',
    searchPlaceholder: '搜索帖子...',
    postTitle: '标题',
    postContent: '内容',
    postType: '帖子类型',
    share: '分享',
    help: '求助',
    tags: '标签',
    publish: '发布',
    pinned: '置顶',
    author: '作者',
    publishTime: '发布时间',
    reply: '回复',
    replies: '回复',
    like: '点赞',
    dislike: '反对',
    favorite: '收藏',
    favorited: '已收藏',
    replySuccess: '回复成功',
    replyFailed: '回复失败',
    operationFailed: '操作失败',
    inputReplyContent: '输入回复内容...',
    postReply: '发表回复',
    cancel: '取消',
    confirmDelete: '确认删除',
    confirmDeleteTopic: '确定要删除这个帖子吗？此操作不可撤销。',
    delete: '删除',
    deleteSuccess: '删除成功',
    deleteFailed: '删除失败',
    loadFailed: '加载失败',
    loading: '加载中...',
    noData: '暂无数据',
    myReplies: '我的回复',
    topicDetail: '帖子详情',
    backToHome: '返回首页',
    images: '图片',
    attachments: '附件',
    themeMode: '主题模式',
    lightMode: '白天模式',
    darkMode: '夜间模式',
    language: '语言',
    chinese: '中文',
    english: 'English',
  },
  en: {
    forumTitle: 'Tire Regulation Forum',
    home: 'Home',
    userCenter: 'User Center',
    settings: 'Settings',
    favorites: 'My Favorites',
    history: 'History',
    messages: 'Messages',
    accountSettings: 'Account Settings',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    newPassword: 'New Password (leave blank to keep current)',
    saveSettings: 'Save Settings',
    loginSuccess: 'Login successful',
    loginFailed: 'Login failed',
    pleaseLogin: 'Please login first',
    createTopic: 'New Post',
    search: 'Search',
    searchPlaceholder: 'Search posts...',
    postTitle: 'Title',
    postContent: 'Content',
    postType: 'Post Type',
    share: 'Share',
    help: 'Help',
    tags: 'Tags',
    publish: 'Publish',
    pinned: 'Pinned',
    author: 'Author',
    publishTime: 'Publish Time',
    reply: 'Reply',
    replies: 'Replies',
    like: 'Like',
    dislike: 'Dislike',
    favorite: 'Favorite',
    favorited: 'Favorited',
    replySuccess: 'Reply successful',
    replyFailed: 'Reply failed',
    operationFailed: 'Operation failed',
    inputReplyContent: 'Enter reply content...',
    postReply: 'Post Reply',
    cancel: 'Cancel',
    confirmDelete: 'Confirm Delete',
    confirmDeleteTopic: 'Are you sure you want to delete this post? This action cannot be undone.',
    delete: 'Delete',
    deleteSuccess: 'Delete successful',
    deleteFailed: 'Delete failed',
    loadFailed: 'Load failed',
    loading: 'Loading...',
    noData: 'No data',
    myReplies: 'My Replies',
    topicDetail: 'Topic Detail',
    backToHome: 'Back to Home',
    images: 'Images',
    attachments: 'Attachments',
    themeMode: 'Theme Mode',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    language: 'Language',
    chinese: '中文',
    english: 'English',
  },
}

export const useTranslation = () => {
  const { language } = useThemeStore()
  return (key: keyof typeof translations.zh) => translations[language][key]
}